name: build and publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QINIU_AK: ${{ secrets.QINIU_AK }}
      QINIU_SK: ${{ secrets.QINIU_SK }}

    strategy:
      matrix:
        node-version: [10.5]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run: npm install

    - name: make directory dist
      run: mkdir dist

    - name: move directory
      run: mv images img-svg nodejs spa testing web selenium dbms mysql01 docs dist

    - name: upload
      run: npx grunt upload
